services:
  admin:
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      PORT:
  api:
    ports:
      - "3001:3000"
      - "9230:9229"
    environment:
      PORT: 3000
      MODE: "local"
      DATABASE_HOST: "db"
      DATABASE_PORT: "3306"
      DATABASE_USERNAME: "tienda"
      DATABASE_PASSWORD: "mia"
      DATABASE_NAME: "tiendamia"
  db:
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "tiendamia"
      MYSQL_USER: "tienda"
      MYSQL_PASSWORD: "mia"
      MYSQL_ROOT_PASSWORD: "lorem"
