ARG nodeVersion=node:18.16.0-alpine

# Install dependencies only when needed
FROM ${nodeVersion} AS deps
RUN apk add --no-cache libc6-compat git
RUN mkdir -p /usr/src/admin && chown -R node:node /usr/src/admin
WORKDIR /usr/src/admin
COPY --chown=node:node package.json yarn.lock ./
RUN ["yarn", "install", "--ignore-scripts", "--frozen-lockfile"]

# Rebuild the source code only when needed
FROM ${nodeVersion} AS builder
WORKDIR /usr/src/admin
COPY --from=deps /usr/src/admin/node_modules ./node_modules
COPY --chown=node:node .. .
ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1
RUN ["yarn", "build"]

# Production image, copy all the files and run next
FROM ${nodeVersion} AS runner
WORKDIR /usr/src/api
ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1
COPY --from=builder /usr/src/admin/public ./public
COPY --from=builder --chown=node:node /usr/src/admin/.next/standalone ./
COPY --from=builder --chown=node:node /usr/src/admin/.next/static ./.next/static
USER node
EXPOSE 3000
ENV PORT 3000
CMD ["node", "server.js"]
